import { NextResponse } from "next/server";

// University Rankings API
// Integrates QS, Times Higher Education, and Shanghai Ranking data

export interface UniversityRanking {
  rank: number;
  name: string;
  country: string;
  countryCode: string;
  region: string;
  type: "public" | "private";
  foundedYear: number;
  worldRankings: {
    qs: number | null;
    the: number | null;
    shanghai: number | null;
  };
  scores: {
    academic: number;
    employer: number;
    facultyStudent: number;
    citations: number;
    internationalFaculty: number;
    internationalStudents: number;
  };
  programs: string[];
  website: string;
  logo: string;
  description: string;
  acceptanceRate: number | null;
  studentCount: number;
  facultyCount: number;
  internationalPercentage: number;
  tuitionRange: string;
  researchOutput: string;
  notableAlumni: string[];
  strengths: string[];
  weaknesses: string[];
  applicationDeadlines: {
    undergraduate: string;
    graduate: string;
  };
  languageRequirements: {
    toefl: number | null;
    ielts: number | null;
    duolingo: number | null;
  };
}

const rankingsDatabase: UniversityRanking[] = [
  {
    rank: 1,
    name: "Massachusetts Institute of Technology",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "private",
    foundedYear: 1861,
    worldRankings: { qs: 1, the: 5, shanghai: 4 },
    scores: { academic: 100, employer: 100, facultyStudent: 100, citations: 99.9, internationalFaculty: 95, internationalStudents: 90 },
    programs: ["Engineering", "Computer Science", "Physics", "Mathematics", "Business", "Architecture", "Linguistics"],
    website: "https://www.mit.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0c/MIT_logo.svg",
    description: "MIT is a world-renowned research university known for its cutting-edge programs in science, engineering, and technology. It has produced numerous Nobel laureates and entrepreneurs.",
    acceptanceRate: 3.96,
    studentCount: 11520,
    facultyCount: 1000,
    internationalPercentage: 34,
    tuitionRange: "$55,000 - $75,000/year",
    researchOutput: "World-leading",
    notableAlumni: ["Kofi Annan", "Buzz Aldrin", "Shirley Ann Jackson", "Benjamin Netanhau"],
    strengths: ["STEM excellence", "Innovation ecosystem", "Industry connections", "Research funding"],
    weaknesses: ["Competitive environment", "Expensive", "Limited liberal arts"],
    applicationDeadlines: { undergraduate: "January 1", graduate: "December 15" },
    languageRequirements: { toefl: 100, ielts: 7.0, duolingo: 120 },
  },
  {
    rank: 2,
    name: "Stanford University",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "private",
    foundedYear: 1885,
    worldRankings: { qs: 3, the: 3, shanghai: 2 },
    scores: { academic: 99, employer: 98, facultyStudent: 98, citations: 99.5, internationalFaculty: 92, internationalStudents: 88 },
    programs: ["Computer Science", "Business", "Engineering", "Law", "Medicine", "Humanities"],
    website: "https://www.stanford.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Seal_of_Leland_Stanford_Junior_University.svg",
    description: "Stanford is one of the world's leading research universities, known for its entrepreneurial culture and groundbreaking discoveries in Silicon Valley.",
    acceptanceRate: 3.68,
    studentCount: 8049,
    facultyCount: 850,
    internationalPercentage: 32,
    tuitionRange: "$56,000 - $78,000/year",
    researchOutput: "World-leading",
    notableAlumni: ["Elon Musk", "Sergey Brin", "Larry Page", "Sandra Day O'Connor"],
    strengths: ["Silicon Valley location", "Entrepreneurship", "Research excellence", "Industry connections"],
    weaknesses: ["Extremely competitive", "High cost of living", "Work-life balance challenges"],
    applicationDeadlines: { undergraduate: "January 2", graduate: "December 1" },
    languageRequirements: { toefl: 100, ielts: 7.0, duolingo: 120 },
  },
  {
    rank: 3,
    name: "University of Oxford",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    type: "public",
    foundedYear: 1096,
    worldRankings: { qs: 5, the: 1, shanghai: 7 },
    scores: { academic: 99, employer: 97, facultyStudent: 95, citations: 98, internationalFaculty: 98, internationalStudents: 95 },
    programs: ["Humanities", "Medicine", "Law", "Sciences", "Social Sciences", "Engineering"],
    website: "https://www.ox.ac.uk",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/University_of_Oxford_logo.svg",
    description: "The University of Oxford is the oldest university in the English-speaking world, with a history spanning over 900 years. It has produced 28 British prime ministers.",
    acceptanceRate: 17.5,
    studentCount: 24520,
    facultyCount: 1800,
    internationalPercentage: 45,
    tuitionRange: "£9,250 - £48,000/year",
    researchOutput: "World-leading",
    notableAlumni: ["Stephen Hawking", "Malala Yousafzai", "Tony Blair", "J.R.R. Tolkien"],
    strengths: ["Academic excellence", "Tutorial system", "Research output", "Global reputation"],
    weaknesses: ["Intense academic pressure", "Tutorial system can be isolating", "High living costs"],
    applicationDeadlines: { undergraduate: "January 15", graduate: "January 15" },
    languageRequirements: { toefl: 110, ielts: 7.5, duolingo: 130 },
  },
  {
    rank: 4,
    name: "Harvard University",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "private",
    foundedYear: 1636,
    worldRankings: { qs: 4, the: 2, shanghai: 1 },
    scores: { academic: 100, employer: 100, facultyStudent: 96, citations: 99, internationalFaculty: 94, internationalStudents: 92 },
    programs: ["Business", "Law", "Medicine", "Engineering", "Arts", "Sciences"],
    website: "https://www.harvard.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg",
    description: "Harvard is the oldest institution of higher education in the United States, renowned for its academic excellence and global influence.",
    acceptanceRate: 3.41,
    studentCount: 23731,
    facultyCount: 2400,
    internationalPercentage: 25,
    tuitionRange: "$54,000 - $76,000/year",
    researchOutput: "World-leading",
    notableAlumni: ["Barack Obama", "Mark Zuckerberg", "Bill Gates", "Natalie Portman"],
    strengths: ["Brand recognition", "Alumni network", "Research funding", "Interdisciplinary approach"],
    weaknesses: ["Grade inflation concerns", "Competitive culture", "Expensive city"],
    applicationDeadlines: { undergraduate: "January 1", graduate: "December 1" },
    languageRequirements: { toefl: 100, ielts: 7.0, duolingo: 120 },
  },
  {
    rank: 5,
    name: "University of Cambridge",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    type: "public",
    foundedYear: 1209,
    worldRankings: { qs: 2, the: 5, shanghai: 4 },
    scores: { academic: 98, employer: 97, facultyStudent: 96, citations: 97, internationalFaculty: 97, internationalStudents: 94 },
    programs: ["Sciences", "Engineering", "Humanities", "Medicine", "Law", "Business"],
    website: "https://www.cam.ac.uk",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Coat_of_Arms_of_the_University_of_Cambridge.svg",
    description: "Cambridge is a world-leading research university with a distinguished history. It has produced more Nobel laureates than any other institution.",
    acceptanceRate: 21,
    studentCount: 24450,
    facultyCount: 1700,
    internationalPercentage: 42,
    tuitionRange: "£9,250 - £45,000/year",
    researchOutput: "World-leading",
    notableAlumni: ["Isaac Newton", "Charles Darwin", "Stephen Hawking", "Alan Turing"],
    strengths: ["Research excellence", "Tutorial system", "Nobel laureates", "Beautiful campus"],
    weaknesses: ["Intense academic pressure", "Limited course flexibility", "High living costs"],
    applicationDeadlines: { undergraduate: "October 15", graduate: "December 3" },
    languageRequirements: { toefl: 110, ielts: 7.5, duolingo: 125 },
  },
  {
    rank: 6,
    name: "California Institute of Technology",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "private",
    foundedYear: 1891,
    worldRankings: { qs: 6, the: 6, shanghai: 6 },
    scores: { academic: 98, employer: 95, facultyStudent: 99, citations: 99, internationalFaculty: 93, internationalStudents: 90 },
    programs: ["Physics", "Engineering", "Computer Science", "Mathematics", "Chemistry", "Biology"],
    website: "https://www.caltech.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Caltech-seal.svg",
    description: "Caltech is a world-renowned science and engineering research and learning institution, known for its rigorous academics and groundbreaking research.",
    acceptanceRate: 2.7,
    studentCount: 2240,
    facultyCount: 300,
    internationalPercentage: 35,
    tuitionRange: "$55,000 - $65,000/year",
    researchOutput: "World-leading",
    notableAlumni: ["Richard Feynman", "Linus Pauling", "Kip Thorne", "George Washington Carver"],
    strengths: ["Small class sizes", "Research opportunities", "Nobel laureates", "STEM excellence"],
    weaknesses: ["Extremely competitive", "Limited social life", "Small campus", "Intense workload"],
    applicationDeadlines: { undergraduate: "January 3", graduate: "December 1" },
    languageRequirements: { toefl: 100, ielts: 7.0, duolingo: 115 },
  },
  {
    rank: 7,
    name: "ETH Zurich",
    country: "Switzerland",
    countryCode: "CH",
    region: "Europe",
    type: "public",
    foundedYear: 1855,
    worldRankings: { qs: 7, the: 11, shanghai: 20 },
    scores: { academic: 97, employer: 96, facultyStudent: 94, citations: 95, internationalFaculty: 98, internationalStudents: 97 },
    programs: ["Engineering", "Computer Science", "Physics", "Mathematics", "Architecture", "Environmental Sciences"],
    website: "https://ethz.ch",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/97/ETH_Zurich_logo.svg",
    description: "ETH Zurich is one of the world's leading universities in science and technology, known for its cutting-edge research and innovation.",
    acceptanceRate: 27,
    studentCount: 24500,
    facultyCount: 530,
    internationalPercentage: 40,
    tuitionRange: "CHF 730 - CHF 1,500/semester",
    researchOutput: "World-leading",
    notableAlumni: ["Albert Einstein", "John von Neumann", "Gerhard Herzberg"],
    strengths: ["Low tuition", "Research excellence", "Innovation", "Beautiful campus"],
    weaknesses: ["German language helpful", "Intense workload", "Competitive environment"],
    applicationDeadlines: { undergraduate: "April 30 (autumn) / November 30 (spring)", graduate: "December 15" },
    languageRequirements: { toefl: 100, ielts: 7.0, duolingo: 120 },
  },
  {
    rank: 8,
    name: "University of Tokyo",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    type: "public",
    foundedYear: 1877,
    worldRankings: { qs: 28, the: 29, shanghai: 26 },
    scores: { academic: 95, employer: 94, facultyStudent: 88, citations: 90, internationalFaculty: 75, internationalStudents: 70 },
    programs: ["Sciences", "Engineering", "Medicine", "Law", "Agriculture", "Humanities"],
    website: "https://www.u-tokyo.ac.jp",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Seal_of_the_University_of_Tokyo.svg",
    description: "The University of Tokyo is Japan's most prestigious university, leading in research across all disciplines and producing numerous Nobel laureates.",
    acceptanceRate: 34,
    studentCount: 28200,
    facultyCount: 2500,
    internationalPercentage: 20,
    tuitionRange: "¥535,800/year (~$4,800)",
    researchOutput: "World-class",
    notableAlumni: ["Akira Kurosawa", "Yukawa Hideki", "12 Nobel laureates"],
    strengths: ["Research excellence", "Low tuition", "Strong alumni network", "Cultural experience"],
    weaknesses: ["Language barrier", "Bureaucratic", "Work culture", "Earthquake risk"],
    applicationDeadlines: { undergraduate: "December 25 (Fall) / September 30 (Spring)", graduate: "Varies by department" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  {
    rank: 9,
    name: "National University of Singapore",
    country: "Singapore",
    countryCode: "SG",
    region: "Asia",
    type: "public",
    foundedYear: 1905,
    worldRankings: { qs: 8, the: 19, shanghai: 71 },
    scores: { academic: 96, employer: 97, facultyStudent: 92, citations: 88, internationalFaculty: 95, internationalStudents: 93 },
    programs: ["Engineering", "Business", "Computer Science", "Medicine", "Law", "Arts"],
    website: "https://www.nus.edu.sg",
    logo: "https://upload.wikimedia.org/wikipedia/en/b/b9/NUS_coat_of_arms.svg",
    description: "NUS is Singapore's flagship university, consistently ranked as the top university in Asia and among the best in the world.",
    acceptanceRate: 25,
    studentCount: 42000,
    facultyCount: 2500,
    internationalPercentage: 30,
    tuitionRange: "S$20,000 - S$50,000/year",
    researchOutput: "World-class",
    notableAlumni: ["Tony Tan", "S. R. Nathan", "Kishore Mahbubani"],
    strengths: ["Global reputation", "Industry connections", "Research output", "Safe environment"],
    weaknesses: ["Expensive city", "Competitive", "Hot climate", "Social restrictions"],
    applicationDeadlines: { undergraduate: "March 31", graduate: "Varies by program" },
    languageRequirements: { toefl: 92, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 10,
    name: "Tsinghua University",
    country: "China",
    countryCode: "CN",
    region: "Asia",
    type: "public",
    foundedYear: 1911,
    worldRankings: { qs: 12, the: 12, shanghai: 23 },
    scores: { academic: 96, employer: 98, facultyStudent: 90, citations: 85, internationalFaculty: 80, internationalStudents: 75 },
    programs: ["Engineering", "Computer Science", "Business", "Sciences", "Architecture", "Humanities"],
    website: "https://www.tsinghua.edu.cn",
    logo: "https://upload.wikimedia.org/wikipedia/en/a/a1/Tsinghua_University_Logo.svg",
    description: "Tsinghua is one of China's most prestigious universities, known for its engineering and computer science programs.",
    acceptanceRate: 35,
    studentCount: 53302,
    facultyCount: 3100,
    internationalPercentage: 15,
    tuitionRange: "¥28,000 - ¥40,000/year (~$4,000-$5,500)",
    researchOutput: "World-class",
    notableAlumni: ["Xi Jinping", "Hu Jintao", "Yang Zhenning"],
    strengths: ["Engineering excellence", "Low tuition", "Strong industry connections", "Research output"],
    weaknesses: ["Language barrier", "Bureaucratic", "Competitive", "Air pollution"],
    applicationDeadlines: { undergraduate: "March 1 (Fall)", graduate: "Varies by program" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  {
    rank: 11,
    name: "Technical University of Munich",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    type: "public",
    foundedYear: 1868,
    worldRankings: { qs: 15, the: 30, shanghai: 50 },
    scores: { academic: 94, employer: 95, facultyStudent: 90, citations: 88, internationalFaculty: 92, internationalStudents: 90 },
    programs: ["Engineering", "Natural Sciences", "Medicine", "Informatics", "Management"],
    website: "https://www.tum.de",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Logo_der_Technischen_Universit%C3%A4t_M%C3%BCnchen.svg",
    description: "TUM is one of Europe's leading technical universities, known for excellence in engineering and the natural sciences.",
    acceptanceRate: 30,
    studentCount: 45600,
    facultyCount: 2800,
    internationalPercentage: 38,
    tuitionRange: "€0 - €3,000/year (mostly free)",
    researchOutput: "Excellent",
    notableAlumni: ["Rudolf Diesel", "Max Planck", "Otto Hahn"],
    strengths: ["No tuition", "Industry partnerships", "Research excellence", "Innovation ecosystem"],
    weaknesses: ["German language helpful", "Bureaucracy", "Competitive programs"],
    applicationDeadlines: { undergraduate: "July 15 (Winter) / January 15 (Summer)", graduate: "Varies" },
    languageRequirements: { toefl: 88, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 12,
    name: "University of Melbourne",
    country: "Australia",
    countryCode: "AU",
    region: "Oceania",
    type: "public",
    foundedYear: 1853,
    worldRankings: { qs: 13, the: 37, shanghai: 35 },
    scores: { academic: 95, employer: 94, facultyStudent: 88, citations: 90, internationalFaculty: 95, internationalStudents: 93 },
    programs: ["Medicine", "Engineering", "Business", "Arts", "Science", "Law"],
    website: "https://unimelb.edu.au",
    logo: "https://upload.wikimedia.org/wikipedia/en/d/d3/University_of_Melbourne_Logo.svg",
    description: "The University of Melbourne is Australia's second-oldest university and consistently ranked as the country's top university.",
    acceptanceRate: 40,
    studentCount: 52000,
    facultyCount: 3500,
    internationalPercentage: 35,
    tuitionRange: "A$20,000 - A$55,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Peter Singer", "Germaine Greer", "22 Nobel laureates"],
    strengths: ["Research excellence", "Quality of life", "Multicultural", "Strong alumni"],
    weaknesses: ["Expensive", "Far from other countries", "Tight housing market"],
    applicationDeadlines: { undergraduate: "October 31 (Semester 1)", graduate: "Varies" },
    languageRequirements: { toefl: 79, ielts: 6.5, duolingo: 105 },
  },
  {
    rank: 13,
    name: "Yonsei University",
    country: "South Korea",
    countryCode: "KR",
    region: "Asia",
    type: "private",
    foundedYear: 1885,
    worldRankings: { qs: 56, the: 78, shanghai: 101-150 },
    scores: { academic: 90, employer: 92, facultyStudent: 85, citations: 82, internationalFaculty: 88, internationalStudents: 85 },
    programs: ["Business", "Medicine", "Engineering", "Liberal Arts", "Science", "Law"],
    website: "https://www.yonsei.ac.kr",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Yonsei_University_emblem.svg",
    description: "Yonsei is one of Korea's most prestigious private universities, known for its global outlook and research excellence.",
    acceptanceRate: 25,
    studentCount: 39000,
    facultyCount: 2200,
    internationalPercentage: 22,
    tuitionRange: "₩6,000,000 - ₩12,000,000/year (~$4,500-$9,000)",
    researchOutput: "Excellent",
    notableAlumni: ["Lee Myung-bak", "Ban Ki-moon", "Shin Kyuk-ho"],
    strengths: ["Global reputation", "Industry connections", "Campus life", "K-culture"],
    weaknesses: ["Language barrier", "Competitive", "Social hierarchy", "Air pollution"],
    applicationDeadlines: { undergraduate: "September 30 (Spring)", graduate: "Varies" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  {
    rank: 14,
    name: "McGill University",
    country: "Canada",
    countryCode: "CA",
    region: "North America",
    type: "public",
    foundedYear: 1821,
    worldRankings: { qs: 30, the: 46, shanghai: 70 },
    scores: { academic: 93, employer: 90, facultyStudent: 88, citations: 88, internationalFaculty: 92, internationalStudents: 90 },
    programs: ["Medicine", "Engineering", "Business", "Arts", "Science", "Law"],
    website: "https://www.mcgill.ca",
    logo: "https://upload.wikimedia.org/wikipedia/en/7/77/McGill_University_coat_of_arms.svg",
    description: "McGill is one of Canada's most prestigious universities, known for its rigorous academics and diverse student body.",
    acceptanceRate: 46,
    studentCount: 39000,
    facultyCount: 1700,
    internationalPercentage: 30,
    tuitionRange: "CAD 20,000 - CAD 55,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Leonard Cohen", "Justin Trudeau", "12 Nobel laureates"],
    strengths: ["Academic excellence", "Research output", "Diversity", "Beautiful campus"],
    weaknesses: ["Expensive city", "Cold winters", "High tuition", "Competitive"],
    applicationDeadlines: { undergraduate: "January 15", graduate: "Varies" },
    languageRequirements: { toefl: 86, ielts: 6.5, duolingo: 115 },
  },
  {
    rank: 15,
    name: "Seoul National University",
    country: "South Korea",
    countryCode: "KR",
    region: "Asia",
    type: "public",
    foundedYear: 1946,
    worldRankings: { qs: 36, the: 62, shanghai: 97 },
    scores: { academic: 92, employer: 93, facultyStudent: 86, citations: 85, internationalFaculty: 80, internationalStudents: 78 },
    programs: ["Engineering", "Business", "Medicine", "Law", "Liberal Arts", "Science"],
    website: "https://www.snu.ac.kr",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Seoul_National_University_emblem.svg",
    description: "SNU is South Korea's flagship national university, consistently ranked as the top university in the country.",
    acceptanceRate: 22,
    studentCount: 31500,
    facultyCount: 2100,
    internationalPercentage: 18,
    tuitionRange: "₩4,000,000 - ₩8,000,000/year (~$3,000-$6,000)",
    researchOutput: "Excellent",
    notableAlumni: ["Ban Ki-moon", "Lee Myung-bak", "Park Geun-hye"],
    strengths: ["Top in Korea", "Research output", "Low tuition", "Strong alumni"],
    weaknesses: ["Language barrier", "Competitive", "Military service", "Air pollution"],
    applicationDeadlines: { undergraduate: "September 30 (Spring) / March 31 (Fall)", graduate: "Varies" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  // ============================================
  // ADDITIONAL EUROPEAN UNIVERSITIES
  // ============================================
  {
    rank: 16,
    name: "EPFL (École Polytechnique Fédérale de Lausanne)",
    country: "Switzerland",
    countryCode: "CH",
    region: "Europe",
    type: "public",
    foundedYear: 1853,
    worldRankings: { qs: 14, the: 40, shanghai: 83 },
    scores: { academic: 94, employer: 93, facultyStudent: 92, citations: 94, internationalFaculty: 98, internationalStudents: 97 },
    programs: ["Engineering", "Computer Science", "Architecture", "Life Sciences", "Physics", "Mathematics"],
    website: "https://www.epfl.ch",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/48/EPFL_logo.svg",
    description: "EPFL is ranked among the top 20 universities globally, specializing in engineering and natural sciences. Located on the shores of Lake Geneva.",
    acceptanceRate: 25,
    studentCount: 12500,
    facultyCount: 350,
    internationalPercentage: 52,
    tuitionRange: "CHF 780 - CHF 1,260/semester",
    researchOutput: "World-leading",
    notableAlumni: ["Jacques Curie", "Pierre-Gilles de Gennes", "Martin Vetterli"],
    strengths: ["Low tuition", "Research excellence", "Innovation", "International environment"],
    weaknesses: ["French language helpful", "Intense workload", "Competitive"],
    applicationDeadlines: { undergraduate: "April 30 (autumn) / November 30 (spring)", graduate: "December 15" },
    languageRequirements: { toefl: 100, ielts: 7.0, duolingo: 120 },
  },
  {
    rank: 17,
    name: "Ludwig Maximilian University of Munich",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    type: "public",
    foundedYear: 1472,
    worldRankings: { qs: 28, the: 32, shanghai: 51 },
    scores: { academic: 93, employer: 91, facultyStudent: 88, citations: 90, internationalFaculty: 88, internationalStudents: 85 },
    programs: ["Medicine", "Law", "Economics", "Humanities", "Sciences", "Social Sciences"],
    website: "https://www.lmu.de",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Logo_Ludwig-Maximilians-Universit%C3%A4t_M%C3%BCnchen.svg",
    description: "LMU Munich is one of Europe's most prestigious universities, consistently ranked among the top 30 globally. Founded in 1472.",
    acceptanceRate: 35,
    studentCount: 52000,
    facultyCount: 3200,
    internationalPercentage: 32,
    tuitionRange: "€0 - €3,000/year (mostly free)",
    researchOutput: "Excellent",
    notableAlumni: ["Pope Benedict XVI", "Konrad Adenauer", "Werner Heisenberg"],
    strengths: ["No tuition", "Historic prestige", "Research excellence", "Strong alumni"],
    weaknesses: ["German language helpful", "Bureaucracy", "Large class sizes"],
    applicationDeadlines: { undergraduate: "July 15 (Winter) / January 15 (Summer)", graduate: "Varies" },
    languageRequirements: { toefl: 88, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 18,
    name: "Heidelberg University",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    type: "public",
    foundedYear: 1386,
    worldRankings: { qs: 32, the: 38, shanghai: 57 },
    scores: { academic: 92, employer: 88, facultyStudent: 90, citations: 92, internationalFaculty: 86, internationalStudents: 84 },
    programs: ["Medicine", "Physics", "Chemistry", "Law", "Humanities", "Sciences"],
    website: "https://www.uni-heidelberg.de",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Logo_Uni_Heidelberg.svg",
    description: "Germany's oldest university (1386), Heidelberg is renowned for its research excellence in medicine, physics, and humanities.",
    acceptanceRate: 40,
    studentCount: 30000,
    facultyCount: 2100,
    internationalPercentage: 28,
    tuitionRange: "€0 - €3,000/year",
    researchOutput: "World-class",
    notableAlumni: ["Robert Bunsen", "Georg Wittig", "6 Nobel laureates"],
    strengths: ["No tuition", "Historic prestige", "Research output", "Beautiful campus"],
    weaknesses: ["German language helpful", "Small city", "Limited programs"],
    applicationDeadlines: { undergraduate: "July 15 (Winter)", graduate: "Varies" },
    languageRequirements: { toefl: 88, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 19,
    name: "University of Amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    region: "Europe",
    type: "public",
    foundedYear: 1632,
    worldRankings: { qs: 53, the: 63, shanghai: 101-150 },
    scores: { academic: 90, employer: 88, facultyStudent: 85, citations: 88, internationalFaculty: 90, internationalStudents: 92 },
    programs: ["Social Sciences", "Humanities", "Law", "Economics", "Medicine", "Sciences"],
    website: "https://www.uva.nl",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Logo_University_of_Amsterdam.svg",
    description: "UvA is one of Europe's largest research universities, ranked in the top 60 globally. Strong in social sciences, humanities, and law.",
    acceptanceRate: 35,
    studentCount: 34000,
    facultyCount: 2200,
    internationalPercentage: 35,
    tuitionRange: "€2,000 - €20,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Baruch Spinoza", "Christiaan Huygens", "Guy Verhofstadt"],
    strengths: ["Diverse programs", "Research output", "International environment", "Location"],
    weaknesses: ["Large class sizes", "Bureaucracy", "Housing shortage"],
    applicationDeadlines: { undergraduate: "May 1 (EU) / January 15 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 92, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 20,
    name: "Delft University of Technology",
    country: "Netherlands",
    countryCode: "NL",
    region: "Europe",
    type: "public",
    foundedYear: 1842,
    worldRankings: { qs: 47, the: 70, shanghai: 101-150 },
    scores: { academic: 91, employer: 92, facultyStudent: 88, citations: 86, internationalFaculty: 88, internationalStudents: 90 },
    programs: ["Engineering", "Architecture", "Computer Science", "Aerospace", "Civil Engineering", "Industrial Design"],
    website: "https://www.tudelft.nl",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/TU_Delft_Logo.svg",
    description: "TU Delft is the largest and oldest technical university in the Netherlands, ranked in the top 15 globally for engineering and technology.",
    acceptanceRate: 30,
    studentCount: 23000,
    facultyCount: 1800,
    internationalPercentage: 38,
    tuitionRange: "€2,000 - €18,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Jacques Gehring", "Antoon Coolen", "Dirk Stikker"],
    strengths: ["Engineering excellence", "Research facilities", "Industry connections", "Innovation"],
    weaknesses: ["Competitive", "Heavy workload", "Limited social sciences"],
    applicationDeadlines: { undergraduate: "May 1 (EU) / January 15 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 92, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 21,
    name: "Sorbonne University",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    type: "public",
    foundedYear: 1257,
    worldRankings: { qs: 35, the: 52, shanghai: 43 },
    scores: { academic: 92, employer: 90, facultyStudent: 86, citations: 90, internationalFaculty: 88, internationalStudents: 86 },
    programs: ["Sciences", "Medicine", "Humanities", "Law", "Engineering", "Social Sciences"],
    website: "https://www.sorbonne-universite.fr",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Sorbonne_logo.svg",
    description: "Sorbonne University is one of the most prestigious universities in France and the world, with roots dating back to 1257.",
    acceptanceRate: 30,
    studentCount: 45000,
    facultyCount: 3200,
    internationalPercentage: 32,
    tuitionRange: "€0 - €10,000/year",
    researchOutput: "World-class",
    notableAlumni: ["Marie Curie", "Simone de Beauvoir", "Claude Bernard"],
    strengths: ["Historic prestige", "Research excellence", "Central location", "Diverse programs"],
    weaknesses: ["French language required for some programs", "Bureaucracy", "Large classes"],
    applicationDeadlines: { undergraduate: "January 15 (EU) / December 15 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 92, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 22,
    name: "École Polytechnique",
    country: "France",
    countryCode: "FR",
    region: "Europe",
    type: "public",
    foundedYear: 1794,
    worldRankings: { qs: 38, the: 90, shanghai: 201-300 },
    scores: { academic: 92, employer: 95, facultyStudent: 94, citations: 85, internationalFaculty: 90, internationalStudents: 92 },
    programs: ["Engineering", "Physics", "Mathematics", "Computer Science", "Economics", "Chemistry"],
    website: "https://www.polytechnique.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/62/Ecole_polytechnique_logo.svg",
    description: "École Polytechnique is France's leading scientific Grande École, ranked #1 in France for engineering and science.",
    acceptanceRate: 10,
    studentCount: 3800,
    facultyCount: 350,
    internationalPercentage: 45,
    tuitionRange: "€0 - €15,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Auguste Comte", "Armand Peugeot", "Léo Lagrange"],
    strengths: ["Elite engineering", "Small class sizes", "Research opportunities", "Industry connections"],
    weaknesses: ["Extremely competitive", "Intense workload", "French language helpful"],
    applicationDeadlines: { undergraduate: "January 15", graduate: "Varies" },
    languageRequirements: { toefl: 92, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 23,
    name: "University of Bologna",
    country: "Italy",
    countryCode: "IT",
    region: "Europe",
    type: "public",
    foundedYear: 1088,
    worldRankings: { qs: 160, the: 185, shanghai: 201-300 },
    scores: { academic: 85, employer: 82, facultyStudent: 80, citations: 82, internationalFaculty: 78, internationalStudents: 80 },
    programs: ["Law", "Medicine", "Engineering", "Humanities", "Agriculture", "Political Science"],
    website: "https://www.unibo.it",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Logo_Alma_Mater_Studiorium_%E2%80%93_Universit%C3%A0_di_Bologna.svg",
    description: "The oldest university in the world (1088), Bologna is a leading research university with strong programs in law, humanities, and sciences.",
    acceptanceRate: 55,
    studentCount: 85000,
    facultyCount: 3500,
    internationalPercentage: 22,
    tuitionRange: "€0 - €5,000/year",
    researchOutput: "Good",
    notableAlumni: ["Dante Alighieri", "Petrarch", "Umberto Eco"],
    strengths: ["Historic prestige", "No tuition", "Diverse programs", "City life"],
    weaknesses: ["Large classes", "Bureaucracy", "Italian language helpful"],
    applicationDeadlines: { undergraduate: "September 1 (EU) / May 31 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  {
    rank: 24,
    name: "Politecnico di Milano",
    country: "Italy",
    countryCode: "IT",
    region: "Europe",
    type: "public",
    foundedYear: 1863,
    worldRankings: { qs: 120, the: 201-250, shanghai: 201-300 },
    scores: { academic: 86, employer: 88, facultyStudent: 84, citations: 80, internationalFaculty: 82, internationalStudents: 85 },
    programs: ["Engineering", "Architecture", "Design", "Computer Science", "Industrial Design"],
    website: "https://www.polimi.it",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/12/Logo_Politecnico_di_Milano.svg",
    description: "Italy's largest technical university, ranked in the top 10 globally for engineering and architecture.",
    acceptanceRate: 40,
    studentCount: 45000,
    facultyCount: 2200,
    internationalPercentage: 25,
    tuitionRange: "€0 - €4,000/year",
    researchOutput: "Good",
    notableAlumni: ["Renzo Piano", "Gio Ponti", "Achille Castiglioni"],
    strengths: ["Engineering excellence", "Design programs", "Industry connections", "No tuition"],
    weaknesses: ["Italian language helpful", "Competitive", "Milan is expensive"],
    applicationDeadlines: { undergraduate: "September 1 (EU) / May 31 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  {
    rank: 25,
    name: "KTH Royal Institute of Technology",
    country: "Sweden",
    countryCode: "SE",
    region: "Europe",
    type: "public",
    foundedYear: 1827,
    worldRankings: { qs: 73, the: 180, shanghai: 201-300 },
    scores: { academic: 88, employer: 90, facultyStudent: 86, citations: 84, internationalFaculty: 88, internationalStudents: 90 },
    programs: ["Engineering", "Computer Science", "Architecture", "Mathematics", "Physics", "Chemical Engineering"],
    website: "https://www.kth.se",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c1/KTH_Royal_Institute_of_Technology_logo.svg",
    description: "KTH is Scandinavia's largest technical university, ranked #1 in Sweden and top 30 globally for engineering and technology.",
    acceptanceRate: 35,
    studentCount: 18000,
    facultyCount: 1200,
    internationalPercentage: 35,
    tuitionRange: "SEK 0 - SEK 155,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Lars Magnus Ericsson", "Gustaf de Laval", "Baltzar von Platen"],
    strengths: ["Engineering excellence", "Innovation", "Industry connections", "English-taught programs"],
    weaknesses: ["Competitive", "Stockholm is expensive", "Cold winters"],
    applicationDeadlines: { undergraduate: "January 15", graduate: "January 15" },
    languageRequirements: { toefl: 90, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 26,
    name: "Lund University",
    country: "Sweden",
    countryCode: "SE",
    region: "Europe",
    type: "public",
    foundedYear: 1666,
    worldRankings: { qs: 85, the: 120, shanghai: 151-200 },
    scores: { academic: 87, employer: 85, facultyStudent: 84, citations: 86, internationalFaculty: 86, internationalStudents: 88 },
    programs: ["Environmental Science", "Law", "Economics", "Medicine", "Engineering", "Humanities"],
    website: "https://www.lunduniversity.lu.se",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/59/Lund_University_seal.svg",
    description: "Lund University is one of Europe's oldest and most prestigious universities, ranked #85 globally.",
    acceptanceRate: 35,
    studentCount: 42000,
    facultyCount: 2500,
    internationalPercentage: 25,
    tuitionRange: "SEK 0 - SEK 145,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Dag Hammarskjöld", "Manne Siegbahn", "Svante Arrhenius"],
    strengths: ["Research excellence", "Campus life", "International environment", "Sustainability"],
    weaknesses: ["Cold winters", "Limited city life", "Competitive"],
    applicationDeadlines: { undergraduate: "January 15", graduate: "January 15" },
    languageRequirements: { toefl: 90, ielts: 6.5, duolingo: 110 },
  },
  {
    rank: 27,
    name: "University of Barcelona",
    country: "Spain",
    countryCode: "ES",
    region: "Europe",
    type: "public",
    foundedYear: 1450,
    worldRankings: { qs: 165, the: 198, shanghai: 201-300 },
    scores: { academic: 84, employer: 82, facultyStudent: 80, citations: 82, internationalFaculty: 80, internationalStudents: 82 },
    programs: ["Medicine", "Humanities", "Sciences", "Law", "Economics", "Education"],
    website: "https://www.ub.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Escudo_de_la_Universidad_de_Barcelona.svg",
    description: "The University of Barcelona is Spain's top university, ranked #165 globally and #1 in Spain.",
    acceptanceRate: 50,
    studentCount: 62000,
    facultyCount: 3200,
    internationalPercentage: 20,
    tuitionRange: "€0 - €3,000/year",
    researchOutput: "Good",
    notableAlumni: ["Santiago Ramón y Cajal", "Pablo Casals", "Joan Miró"],
    strengths: ["Historic prestige", "No tuition", "Diverse programs", "Barcelona location"],
    weaknesses: ["Large classes", "Spanish language helpful", "Bureaucracy"],
    applicationDeadlines: { undergraduate: "June 30 (EU) / May 31 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  {
    rank: 28,
    name: "University of Vienna",
    country: "Austria",
    countryCode: "AT",
    region: "Europe",
    type: "public",
    foundedYear: 1365,
    worldRankings: { qs: 137, the: 148, shanghai: 151-200 },
    scores: { academic: 86, employer: 84, facultyStudent: 82, citations: 84, internationalFaculty: 85, internationalStudents: 88 },
    programs: ["Law", "Humanities", "Sciences", "Medicine", "Social Sciences", "Business"],
    website: "https://www.univie.ac.at",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Logo_Universit%C3%A4t_Wien.svg",
    description: "The University of Vienna is Austria's largest and oldest university (1365), ranked in the top 150 globally.",
    acceptanceRate: 45,
    studentCount: 92000,
    facultyCount: 4000,
    internationalPercentage: 28,
    tuitionRange: "€0 - €5,000/year",
    researchOutput: "Excellent",
    notableAlumni: ["Ludwig Boltzmann", "Karl Popper", "Lise Meitner"],
    strengths: ["Historic prestige", "No tuition", "Vienna location", "Diverse programs"],
    weaknesses: ["German language required for some programs", "Large classes", "Bureaucracy"],
    applicationDeadlines: { undergraduate: "June 30 (EU) / May 31 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
  {
    rank: 29,
    name: "University of Warsaw",
    country: "Poland",
    countryCode: "PL",
    region: "Europe",
    type: "public",
    foundedYear: 1816,
    worldRankings: { qs: 266, the: 501-600, shanghai: 401-500 },
    scores: { academic: 80, employer: 78, facultyStudent: 76, citations: 78, internationalFaculty: 75, internationalStudents: 78 },
    programs: ["Economics", "Law", "Social Sciences", "Humanities", "Sciences", "Management"],
    website: "https://www.uw.edu.pl",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/48/Uniwersytet_Warszawski_logo.svg",
    description: "Poland's largest and most prestigious university, ranked #266 globally.",
    acceptanceRate: 45,
    studentCount: 45000,
    facultyCount: 2200,
    internationalPercentage: 15,
    tuitionRange: "PLN 0 - PLN 20,000/year",
    researchOutput: "Good",
    notableAlumni: ["Marie Curie", "Joseph Rotblat", "Yehuda Bacon"],
    strengths: ["No tuition for EU", "Diverse programs", "Warsaw location", "Affordable"],
    weaknesses: ["Polish language helpful", "Lower rankings", "Limited English programs"],
    applicationDeadlines: { undergraduate: "July 15 (EU) / June 15 (non-EU)", graduate: "Varies" },
    languageRequirements: { toefl: 80, ielts: 6.0, duolingo: 100 },
  },
];

// GET /api/rankings - Get university rankings
export async function GET(request: Request) {
  try {
    const url = new URL(request.url);
    const rankingSource = url.searchParams.get("source") || "composite";
    const country = url.searchParams.get("country");
    const region = url.searchParams.get("region");
    const limit = parseInt(url.searchParams.get("limit") || "50");
    const sortBy = url.searchParams.get("sortBy") || "rank";

    let results = [...rankingsDatabase];

    if (country) {
      results = results.filter((u) => u.country.toLowerCase().includes(country.toLowerCase()));
    }

    if (region) {
      results = results.filter((u) => u.region.toLowerCase() === region.toLowerCase());
    }

    // Sort by specific ranking source
    if (sortBy === "qs") results.sort((a, b) => (a.worldRankings.qs || 999) - (b.worldRankings.qs || 999));
    else if (sortBy === "the") results.sort((a, b) => (a.worldRankings.the || 999) - (b.worldRankings.the || 999));
    else if (sortBy === "shanghai") results.sort((a, b) => (a.worldRankings.shanghai || 999) - (b.worldRankings.shanghai || 999));
    else results.sort((a, b) => a.rank - b.rank);

    results = results.slice(0, limit);

    return NextResponse.json({
      success: true,
      data: results,
      meta: {
        total: results.length,
        sources: ["QS World University Rankings", "Times Higher Education", "Shanghai Ranking (ARWU)"],
        lastUpdated: "2025-01-01",
      },
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : "Failed to fetch rankings" },
      { status: 500 }
    );
  }
}
