import { NextResponse } from "next/server";

// University data
const universities: Record<string, {
  id: string;
  name: string;
  slug: string;
  country: string;
  countryCode: string;
  city: string;
  website: string;
  logo: string;
  description: string;
  ranking?: number;
  accreditation: string[];
  verified: boolean;
  scholarshipCount: number;
  studentCount?: number;
  foundedYear?: number;
  type: "public" | "private" | "community" | "research";
  specialties: string[];
  createdAt: string;
  updatedAt: string;
}> = {
  "massachusetts-institute-of-technology": {
    id: "uni-1",
    name: "Massachusetts Institute of Technology",
    slug: "massachusetts-institute-of-technology",
    country: "United States",
    countryCode: "US",
    city: "Cambridge",
    website: "https://www.mit.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/0c/MIT_logo.svg",
    description: "MIT is a world-renowned research university known for its cutting-edge programs in science, engineering, and technology.",
    ranking: 1,
    accreditation: ["NEASC", "ABET"],
    verified: true,
    scholarshipCount: 45,
    studentCount: 11520,
    foundedYear: 1861,
    type: "research",
    specialties: ["Engineering", "Computer Science", "Physics", "Mathematics", "Business"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "stanford-university": {
    id: "uni-2",
    name: "Stanford University",
    slug: "stanford-university",
    country: "United States",
    countryCode: "US",
    city: "Stanford",
    website: "https://www.stanford.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Seal_of_Leland_Stanford_Junior_University.svg",
    description: "Stanford is one of the world's leading research universities, known for its entrepreneurial culture and groundbreaking discoveries.",
    ranking: 2,
    accreditation: ["WSCUC"],
    verified: true,
    scholarshipCount: 38,
    studentCount: 8049,
    foundedYear: 1885,
    type: "private",
    specialties: ["Computer Science", "Business", "Engineering", "Law", "Medicine"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "university-of-oxford": {
    id: "uni-3",
    name: "University of Oxford",
    slug: "university-of-oxford",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Oxford",
    website: "https://www.ox.ac.uk",
    logo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/University_of_Oxford_logo.svg",
    description: "The University of Oxford is the oldest university in the English-speaking world, with a history spanning over 900 years.",
    ranking: 3,
    accreditation: ["QAA"],
    verified: true,
    scholarshipCount: 52,
    studentCount: 24520,
    foundedYear: 1096,
    type: "public",
    specialties: ["Humanities", "Medicine", "Law", "Sciences", "Social Sciences"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "technical-university-of-munich": {
    id: "uni-4",
    name: "Technical University of Munich",
    slug: "technical-university-of-munich",
    country: "Germany",
    countryCode: "DE",
    city: "Munich",
    website: "https://www.tum.de",
    logo: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Logo_der_Technischen_Universit%C3%A4t_M%C3%BCnchen.svg",
    description: "TUM is one of Europe's leading technical universities, known for excellence in engineering and the natural sciences.",
    ranking: 15,
    accreditation: ["ACQUIN"],
    verified: true,
    scholarshipCount: 35,
    studentCount: 45600,
    foundedYear: 1868,
    type: "public",
    specialties: ["Engineering", "Natural Sciences", "Medicine", "Informatics", "Management"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "university-of-tokyo": {
    id: "uni-5",
    name: "University of Tokyo",
    slug: "university-of-tokyo",
    country: "Japan",
    countryCode: "JP",
    city: "Tokyo",
    website: "https://www.u-tokyo.ac.jp",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Seal_of_the_University_of_Tokyo.svg",
    description: "The University of Tokyo is Japan's most prestigious university, leading in research across all disciplines.",
    ranking: 20,
    accreditation: ["JUAA"],
    verified: true,
    scholarshipCount: 28,
    studentCount: 28200,
    foundedYear: 1877,
    type: "public",
    specialties: ["Sciences", "Engineering", "Medicine", "Law", "Agriculture"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "seoul-national-university": {
    id: "uni-6",
    name: "Seoul National University",
    slug: "seoul-national-university",
    country: "South Korea",
    countryCode: "KR",
    city: "Seoul",
    website: "https://www.snu.ac.kr",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Seoul_National_University_emblem.svg",
    description: "SNU is South Korea's flagship national university, consistently ranked as the top university in the country.",
    ranking: 25,
    accreditation: ["KCUE"],
    verified: true,
    scholarshipCount: 42,
    studentCount: 31500,
    foundedYear: 1946,
    type: "public",
    specialties: ["Engineering", "Business", "Medicine", "Law", "Liberal Arts"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  // ============================================
  // EUROPEAN UNIVERSITIES
  // ============================================
  "eth-zurich": {
    id: "uni-10",
    name: "ETH Zurich (Swiss Federal Institute of Technology)",
    slug: "eth-zurich",
    country: "Switzerland",
    countryCode: "CH",
    city: "Zurich",
    website: "https://www.ethz.ch",
    logo: "https://upload.wikimedia.org/wikipedia/commons/9/92/ETH_Zurich_logo_black.svg",
    description: "ETH Zurich is one of the world's leading universities in science and technology, ranked #7 globally. Known for groundbreaking research in engineering, architecture, mathematics, and natural sciences.",
    ranking: 7,
    accreditation: ["swissuniversities"],
    verified: true,
    scholarshipCount: 28,
    studentCount: 23000,
    foundedYear: 1855,
    type: "public",
    specialties: ["Engineering", "Computer Science", "Architecture", "Mathematics", "Physics", "Chemistry"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "epfl": {
    id: "uni-11",
    name: "EPFL (École Polytechnique Fédérale de Lausanne)",
    slug: "epfl",
    country: "Switzerland",
    countryCode: "CH",
    city: "Lausanne",
    website: "https://www.epfl.ch",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/48/EPFL_logo.svg",
    description: "EPFL is ranked among the top 20 universities globally, specializing in engineering and natural sciences. Located on the shores of Lake Geneva.",
    ranking: 14,
    accreditation: ["swissuniversities"],
    verified: true,
    scholarshipCount: 22,
    studentCount: 12500,
    foundedYear: 1853,
    type: "public",
    specialties: ["Engineering", "Computer Science", "Architecture", "Life Sciences", "Physics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "ludwig-maximilians-university": {
    id: "uni-12",
    name: "Ludwig Maximilian University of Munich",
    slug: "ludwig-maximilians-university",
    country: "Germany",
    countryCode: "DE",
    city: "Munich",
    website: "https://www.lmu.de",
    logo: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Logo_Ludwig-Maximilians-Universit%C3%A4t_M%C3%BCnchen.svg",
    description: "LMU Munich is one of Europe's most prestigious universities, consistently ranked among the top 30 globally. Strong in humanities, law, economics, and medicine.",
    ranking: 28,
    accreditation: ["ACQUIN"],
    verified: true,
    scholarshipCount: 32,
    studentCount: 52000,
    foundedYear: 1472,
    type: "public",
    specialties: ["Medicine", "Law", "Economics", "Humanities", "Sciences", "Social Sciences"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "heidelberg-university": {
    id: "uni-13",
    name: "Heidelberg University",
    slug: "heidelberg-university",
    country: "Germany",
    countryCode: "DE",
    city: "Heidelberg",
    website: "https://www.uni-heidelberg.de",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Logo_Uni_Heidelberg.svg",
    description: "Germany's oldest university (1386), Heidelberg is renowned for its research excellence in medicine, physics, and humanities.",
    ranking: 32,
    accreditation: ["ACQUIN"],
    verified: true,
    scholarshipCount: 25,
    studentCount: 30000,
    foundedYear: 1386,
    type: "public",
    specialties: ["Medicine", "Physics", "Chemistry", "Law", "Humanities"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "university-of-amsterdam": {
    id: "uni-14",
    name: "University of Amsterdam",
    slug: "university-of-amsterdam",
    country: "Netherlands",
    countryCode: "NL",
    city: "Amsterdam",
    website: "https://www.uva.nl",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Logo_University_of_Amsterdam.svg",
    description: "UvA is one of Europe's largest research universities, ranked in the top 60 globally. Strong in social sciences, humanities, and law.",
    ranking: 53,
    accreditation: ["NVAO"],
    verified: true,
    scholarshipCount: 20,
    studentCount: 34000,
    foundedYear: 1632,
    type: "public",
    specialties: ["Social Sciences", "Humanities", "Law", "Economics", "Medicine"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "delft-university-of-technology": {
    id: "uni-15",
    name: "Delft University of Technology",
    slug: "delft-university-of-technology",
    country: "Netherlands",
    countryCode: "NL",
    city: "Delft",
    website: "https://www.tudelft.nl",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/TU_Delft_Logo.svg",
    description: "TU Delft is the largest and oldest technical university in the Netherlands, ranked in the top 15 globally for engineering and technology.",
    ranking: 47,
    accreditation: ["NVAO"],
    verified: true,
    scholarshipCount: 18,
    studentCount: 23000,
    foundedYear: 1842,
    type: "public",
    specialties: ["Engineering", "Architecture", "Computer Science", "Aerospace", "Civil Engineering"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "sorbonne-university": {
    id: "uni-16",
    name: "Sorbonne University",
    slug: "sorbonne-university",
    country: "France",
    countryCode: "FR",
    city: "Paris",
    website: "https://www.sorbonne-universite.fr",
    logo: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Sorbonne_logo.svg",
    description: "Sorbonne University is one of the most prestigious universities in France and the world, with roots dating back to 1257. Strong in sciences, medicine, and humanities.",
    ranking: 35,
    accreditation: ["CTI", "HCERES"],
    verified: true,
    scholarshipCount: 30,
    studentCount: 45000,
    foundedYear: 1257,
    type: "public",
    specialties: ["Sciences", "Medicine", "Humanities", "Law", "Engineering"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "ecole-polytechnique": {
    id: "uni-17",
    name: "École Polytechnique",
    slug: "ecole-polytechnique",
    country: "France",
    countryCode: "FR",
    city: "Palaiseau",
    website: "https://www.polytechnique.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/6/62/Ecole_polytechnique_logo.svg",
    description: "École Polytechnique is France's leading scientific Grande École, ranked #1 in France for engineering and science.",
    ranking: 38,
    accreditation: ["CTI"],
    verified: true,
    scholarshipCount: 15,
    studentCount: 3800,
    foundedYear: 1794,
    type: "public",
    specialties: ["Engineering", "Physics", "Mathematics", "Computer Science", "Economics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "university-of-bologna": {
    id: "uni-18",
    name: "University of Bologna",
    slug: "university-of-bologna",
    country: "Italy",
    countryCode: "IT",
    city: "Bologna",
    website: "https://www.unibo.it",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Logo_Alma_Mater_Studiorium_%E2%80%93_Universit%C3%A0_di_Bologna.svg",
    description: "The oldest university in the world (1088), Bologna is a leading research university with strong programs in law, humanities, and sciences.",
    ranking: 160,
    accreditation: ["ANVUR"],
    verified: true,
    scholarshipCount: 35,
    studentCount: 85000,
    foundedYear: 1088,
    type: "public",
    specialties: ["Law", "Medicine", "Engineering", "Humanities", "Agriculture"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "politecnico-di-milano": {
    id: "uni-19",
    name: "Politecnico di Milano",
    slug: "politecnico-di-milano",
    country: "Italy",
    countryCode: "IT",
    city: "Milan",
    website: "https://www.polimi.it",
    logo: "https://upload.wikimedia.org/wikipedia/commons/1/12/Logo_Politecnico_di_Milano.svg",
    description: "Italy's largest technical university, ranked in the top 10 globally for engineering and architecture.",
    ranking: 120,
    accreditation: ["ANVUR"],
    verified: true,
    scholarshipCount: 22,
    studentCount: 45000,
    foundedYear: 1863,
    type: "public",
    specialties: ["Engineering", "Architecture", "Design", "Computer Science"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "kth-royal-institute-of-technology": {
    id: "uni-20",
    name: "KTH Royal Institute of Technology",
    slug: "kth-royal-institute-of-technology",
    country: "Sweden",
    countryCode: "SE",
    city: "Stockholm",
    website: "https://www.kth.se",
    logo: "https://upload.wikimedia.org/wikipedia/commons/c/c1/KTH_Royal_Institute_of_Technology_logo.svg",
    description: "KTH is Scandinavia's largest technical university, ranked #1 in Sweden and top 30 globally for engineering and technology.",
    ranking: 73,
    accreditation: ["UKÄ"],
    verified: true,
    scholarshipCount: 18,
    studentCount: 18000,
    foundedYear: 1827,
    type: "public",
    specialties: ["Engineering", "Computer Science", "Architecture", "Mathematics", "Physics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "lund-university": {
    id: "uni-21",
    name: "Lund University",
    slug: "lund-university",
    country: "Sweden",
    countryCode: "SE",
    city: "Lund",
    website: "https://www.lunduniversity.lu.se",
    logo: "https://upload.wikimedia.org/wikipedia/commons/5/59/Lund_University_seal.svg",
    description: "Lund University is one of Europe's oldest and most prestigious universities, ranked #85 globally. Strong in environmental science, law, and economics.",
    ranking: 85,
    accreditation: ["UKÄ"],
    verified: true,
    scholarshipCount: 20,
    studentCount: 42000,
    foundedYear: 1666,
    type: "public",
    specialties: ["Environmental Science", "Law", "Economics", "Medicine", "Engineering"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "university-of-barcelona": {
    id: "uni-22",
    name: "University of Barcelona",
    slug: "university-of-barcelona",
    country: "Spain",
    countryCode: "ES",
    city: "Barcelona",
    website: "https://www.ub.edu",
    logo: "https://upload.wikimedia.org/wikipedia/commons/3/3f/Escudo_de_la_Universidad_de_Barcelona.svg",
    description: "The University of Barcelona is Spain's top university, ranked #165 globally and #1 in Spain. Strong in humanities, sciences, and medicine.",
    ranking: 165,
    accreditation: ["ANECA"],
    verified: true,
    scholarshipCount: 25,
    studentCount: 62000,
    foundedYear: 1450,
    type: "public",
    specialties: ["Medicine", "Humanities", "Sciences", "Law", "Economics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "university-of-vienna": {
    id: "uni-23",
    name: "University of Vienna",
    slug: "university-of-vienna",
    country: "Austria",
    countryCode: "AT",
    city: "Vienna",
    website: "https://www.univie.ac.at",
    logo: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Logo_Universit%C3%A4t_Wien.svg",
    description: "The University of Vienna is Austria's largest and oldest university (1365), ranked in the top 150 globally. Strong in humanities, law, and sciences.",
    ranking: 137,
    accreditation: ["OEQA"],
    verified: true,
    scholarshipCount: 20,
    studentCount: 92000,
    foundedYear: 1365,
    type: "public",
    specialties: ["Law", "Humanities", "Sciences", "Medicine", "Social Sciences"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  "university-of-warsaw": {
    id: "uni-24",
    name: "University of Warsaw",
    slug: "university-of-warsaw",
    country: "Poland",
    countryCode: "PL",
    city: "Warsaw",
    website: "https://www.uw.edu.pl",
    logo: "https://upload.wikimedia.org/wikipedia/commons/4/48/Uniwersytet_Warszawski_logo.svg",
    description: "Poland's largest and most prestigious university, ranked #266 globally. Strong in economics, law, and social sciences.",
    ranking: 266,
    accreditation: ["NAK"],
    verified: true,
    scholarshipCount: 18,
    studentCount: 45000,
    foundedYear: 1816,
    type: "public",
    specialties: ["Economics", "Law", "Social Sciences", "Humanities", "Sciences"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
};

// GET /api/universities - list all universities
export async function GET(request: Request) {
  try {
    const url = new URL(request.url);
    const search = url.searchParams.get("search");
    const country = url.searchParams.get("country");
    const type = url.searchParams.get("type");
    const limit = parseInt(url.searchParams.get("limit") || "50");

    let results = Object.values(universities);

    if (search) {
      const q = search.toLowerCase();
      results = results.filter(
        (u) =>
          u.name.toLowerCase().includes(q) ||
          u.country.toLowerCase().includes(q) ||
          u.city.toLowerCase().includes(q) ||
          u.specialties.some((s) => s.toLowerCase().includes(q))
      );
    }

    if (country) {
      results = results.filter((u) => u.country.toLowerCase() === country.toLowerCase());
    }

    if (type) {
      results = results.filter((u) => u.type === type);
    }

    results = results.slice(0, limit);

    return NextResponse.json({
      success: true,
      data: results,
      pagination: {
        total: results.length,
        page: 1,
        limit,
        totalPages: 1,
      },
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : "Failed to fetch universities" },
      { status: 500 }
    );
  }
}
