import { NextResponse } from "next/server";

// Comprehensive Scholarship Database
// DAAD, Erasmus+, Chevening, Commonwealth, Fulbright, MEXT, CSC China, Stipendium Hungaricum

export interface Scholarship {
  id: string;
  name: string;
  slug: string;
  provider: string;
  country: string;
  countryCode: string;
  region: string;
  type: "government" | "university" | "organization" | "research";
  degree: string[];
  funding: "fully_funded" | "partial" | "tuition_only" | "stipend";
  amount: string;
  deadline: string;
  deadlineType: "annual" | "rolling" | "fixed";
  eligibility: {
    nationality: string[];
    ageLimit: number | null;
    gpa: number | null;
    workExperience: number | null;
    languageRequirements: string[];
    documents: string[];
  };
  benefits: string[];
  applicationUrl: string;
  contactEmail: string;
  description: string;
  tips: string[];
  successRate: number;
  competitive: boolean;
  renewable: boolean;
  duration: string;
  coverage: string[];
}

const scholarshipDatabase: Scholarship[] = [
  {
    id: "sch-fulbright",
    name: "Fulbright Foreign Student Program",
    slug: "fulbright-foreign-student-program",
    provider: "U.S. Department of State",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "government",
    degree: ["masters", "phd", "postdoc"],
    funding: "fully_funded",
    amount: "Full tuition + $20,000/year stipend + airfare + health insurance",
    deadline: "February 1 - October 1 (varies by country)",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["Non-US citizens from 160+ countries"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["TOEFL 80+ or IELTS 6.5+"],
      documents: ["Academic transcripts", "Degree certificate", "TOEFL/IELTS scores", "3 letters of recommendation", "Personal statement", "Study/research proposal"],
    },
    benefits: ["Full tuition and fees", "Monthly living stipend", "Airfare to/from US", "Health insurance", "Book and supply allowance", "Pre-academic programming", "Cultural enrichment activities"],
    applicationUrl: "https://foreign.fulbrightonline.org/",
    contactEmail: "fulbright@state.gov",
    description: "The Fulbright Program provides grants for individually designed study/research projects. Students design their own academic program and arrange affiliation with a U.S. university.",
    tips: ["Start 12-18 months before intended start", "Tailor proposal to your field", "Show leadership potential", "Demonstrate cultural exchange interest", "Get strong recommendations"],
    successRate: 20,
    competitive: true,
    renewable: false,
    duration: "1-2 years",
    coverage: ["Tuition", "Living expenses", "Travel", "Health insurance"],
  },
  {
    id: "sch-daad",
    name: "DAAD German Academic Exchange Service",
    slug: "daad-german-academic-exchange-service",
    provider: "DAAD (German Academic Exchange Service)",
    country: "Germany",
    countryCode: "DE",
    region: "Europe",
    type: "government",
    degree: ["masters", "phd", "postdoc", "research"],
    funding: "fully_funded",
    amount: "€850-€1,200/month stipend + tuition + travel + health insurance",
    deadline: "Varies by program (October-March)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["All countries except Germany"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: 2,
      languageRequirements: ["German (TestDaF 4x4) or English (IELTS 6.0+)"],
      documents: ["Academic transcripts", "Degree certificate", "Language certificates", "CV", "Motivation letter", "Research proposal (for PhD)"],
    },
    benefits: ["Monthly stipend €850-€1,200", "Full tuition at public universities", "Health insurance", "Travel allowance", "German language course", "Study allowance"],
    applicationUrl: "https://www.daad.de/en/",
    contactEmail: "post@daad.de",
    description: "DAAD is the world's largest funding organization for international academic exchange. It supports over 100,000 students and researchers annually.",
    tips: ["Apply early - 6-12 months before", "Check specific program deadlines", "Strong German skills help", "Research German universities first", "Contact potential supervisors"],
    successRate: 25,
    competitive: true,
    renewable: false,
    duration: "1-3 years",
    coverage: ["Stipend", "Tuition", "Travel", "Health insurance"],
  },
  {
    id: "sch-chevening",
    name: "Chevening Scholarship",
    slug: "chevening-scholarship",
    provider: "UK Government (FCDO)",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    type: "government",
    degree: ["masters"],
    funding: "fully_funded",
    amount: "Full tuition + £1,163/month stipend + airfare + travel grant",
    deadline: "November 1",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["160+ Chevening-eligible countries"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: 2,
      languageRequirements: ["IELTS 6.5+ (all bands 5.5+)"],
      documents: ["Academic transcripts", "Degree certificate", "IELTS scores", "3 references", "Leadership statement", "Study plan"],
    },
    benefits: ["Full tuition fees", "Monthly living allowance £1,163", "Economy class return airfare", "Travel grant for arrival", "Thesis/project grant", "Access to exclusive networking", "Chevening alumni network"],
    applicationUrl: "https://www.chevening.org/",
    contactEmail: "enquiries@chevening.org",
    description: "Chevening is the UK government's international awards programme aimed at developing global leaders. It offers fully funded scholarships for one-year Master's degrees.",
    tips: ["Demonstrate leadership potential", "Show networking skills", "Have clear career goals", "Apply to 4 UK universities", "Prepare strong essays"],
    successRate: 15,
    competitive: true,
    renewable: false,
    duration: "1 year",
    coverage: ["Tuition", "Living expenses", "Travel"],
  },
  {
    id: "sch-erasmus",
    name: "Erasmus Mundus Joint Master Degree",
    slug: "erasmus-mundus-joint-master-degree",
    provider: "European Commission",
    country: "European Union",
    countryCode: "EU",
    region: "Europe",
    type: "government",
    degree: ["masters"],
    funding: "fully_funded",
    amount: "€1,400/month + tuition + travel + installation costs",
    deadline: "January 15 - March 15 (varies by consortium)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["All countries worldwide"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["Varies by program (English or European language)"],
      documents: ["Academic transcripts", "Degree certificate", "Language certificate", "CV", "Motivation letter", "2 references"],
    },
    benefits: ["Monthly allowance €1,400", "Full tuition coverage", "Travel costs", "Installation costs", "Health insurance", "Study in 2-3 EU countries"],
    applicationUrl: "https://erasmus-plus.ec.europa.eu/",
    contactEmail: "eac-erasmus-mundus@ec.europa.eu",
    description: "Erasmus Mundus offers joint Master's degrees delivered by consortia of European universities. Students study in at least two EU countries.",
    tips: ["Apply to multiple consortia", "Check specific program requirements", "Early application helps", "Strong motivation letter crucial", "Highlight international experience"],
    successRate: 20,
    competitive: true,
    renewable: false,
    duration: "1-2 years",
    coverage: ["Tuition", "Living expenses", "Travel"],
  },
  {
    id: "sch-commonwealth",
    name: "Commonwealth Scholarship",
    slug: "commonwealth-scholarship",
    provider: "Commonwealth Scholarship Commission (UK)",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    type: "government",
    degree: ["masters", "phd"],
    funding: "fully_funded",
    amount: "Full tuition + £1,236/month stipend + airfare + thesis grant",
    deadline: "December (varies by nominating body)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["Commonwealth countries (54 countries)"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["English proficiency"],
      documents: ["Academic transcripts", "Degree certificate", "References", "Study proposal", "Development impact statement"],
    },
    benefits: ["Full tuition fees", "Monthly stipend £1,236", "Return airfare", "Thesis grant", "Warm clothing allowance", "Study travel grant"],
    applicationUrl: "https://cscuk.fcdo.gov.uk/scholarships/",
    contactEmail: "csc@fcdo.gov.uk",
    description: "The Commonwealth Scholarship Commission awards scholarships for Master's and PhD study at UK universities for students from Commonwealth countries.",
    tips: ["Apply through your national nominating body", "Show development impact potential", "Demonstrate leadership", "Strong academic record", "Clear career plan"],
    successRate: 15,
    competitive: true,
    renewable: false,
    duration: "1-3 years",
    coverage: ["Tuition", "Living expenses", "Travel"],
  },
  {
    id: "sch-mext",
    name: "MEXT Japanese Government Scholarship",
    slug: "mext-japanese-government-scholarship",
    provider: "Ministry of Education, Culture, Sports, Science and Technology (Japan)",
    country: "Japan",
    countryCode: "JP",
    region: "Asia",
    type: "government",
    degree: ["bachelors", "masters", "phd", "research"],
    funding: "fully_funded",
    amount: "¥117,000-¥145,000/month + tuition + travel + housing",
    deadline: "April 15 (Embassy) / varies (University)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["Countries with diplomatic relations with Japan"],
      ageLimit: 35,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["Japanese (JLPT N2+) or English (IELTS 6.0+)"],
      documents: ["Academic transcripts", "Degree certificate", "Language certificate", "Research proposal", "Health certificate", "Recommendation letters"],
    },
    benefits: ["Monthly stipend ¥117,000-¥145,000", "Full tuition coverage", "Round-trip airfare", "Housing support", "Japanese language training", "Settling-in allowance"],
    applicationUrl: "https://www.studyinjapan.go.jp/en/smap-stopj-applications-scholarship.html",
    contactEmail: "ryugaku@mext.go.jp",
    description: "MEXT scholarships are awarded by the Japanese government to international students who want to study at Japanese universities.",
    tips: ["Apply through Japanese embassy", "Japanese language skills helpful", "Research Japanese universities first", "Prepare for written exam", "Show interest in Japan"],
    successRate: 25,
    competitive: true,
    renewable: false,
    duration: "2-5 years",
    coverage: ["Stipend", "Tuition", "Travel", "Housing"],
  },
  {
    id: "sch-csc",
    name: "Chinese Government Scholarship (CSC)",
    slug: "chinese-government-scholarship-csc",
    provider: "China Scholarship Council",
    country: "China",
    countryCode: "CN",
    region: "Asia",
    type: "government",
    degree: ["bachelors", "masters", "phd"],
    funding: "fully_funded",
    amount: "¥2,500-¥3,500/month + tuition + housing + insurance",
    deadline: "April 15",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["All countries worldwide"],
      ageLimit: 40,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["Chinese (HSK 4+) or English (IELTS 6.0+)"],
      documents: ["Academic transcripts", "Degree certificate", "Language certificate", "Study plan", "Research proposal (PhD)", "Physical exam form", "Non-criminal record"],
    },
    benefits: ["Monthly stipend ¥2,500-¥3,500", "Full tuition coverage", "Free on-campus housing", "Comprehensive medical insurance", "Settling-in allowance"],
    applicationUrl: "https://www.campuschina.org/",
    contactEmail: "studyinchina@csc.edu.cn",
    description: "CSC scholarships are offered by the Chinese government to international students for study at Chinese universities.",
    tips: ["Apply through Chinese embassy or university", "Chinese language skills help", "Research partner universities", "Prepare strong study plan", "Get recommendations"],
    successRate: 30,
    competitive: true,
    renewable: true,
    duration: "2-5 years",
    coverage: ["Stipend", "Tuition", "Housing", "Insurance"],
  },
  {
    id: "sch-stipendium",
    name: "Stipendium Hungaricum Scholarship",
    slug: "stipendium-hungaricum-scholarship",
    provider: "Hungarian Government (Tempus Public Foundation)",
    country: "Hungary",
    countryCode: "HU",
    region: "Europe",
    type: "government",
    degree: ["bachelors", "masters", "phd"],
    funding: "fully_funded",
    amount: "€150-€250/month + tuition + housing + insurance",
    deadline: "January 15",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["Partner country nationals (80+ countries)"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["English (IELTS 5.5+ or equivalent)"],
      documents: ["Academic transcripts", "Degree certificate", "Language certificate", "CV", "Motivation letter", "Medical certificate"],
    },
    benefits: ["Monthly stipend €150-€250", "Full tuition coverage", "Free dormitory accommodation", "Health insurance", "Hungarian language course"],
    applicationUrl: "https://stipendiumhungaricum.hu/",
    contactEmail: "info@stipendiumhungaricum.hu",
    description: "The Stipendium Hungaricum Scholarship Program is established by the Hungarian Government to promote international cooperation.",
    tips: ["Apply through Hungarian embassy", "Choose from 600+ programs", "Hungarian language course included", "Central European location", "Affordable living costs"],
    successRate: 35,
    competitive: false,
    renewable: true,
    duration: "2-4 years",
    coverage: ["Tuition", "Housing", "Stipend", "Insurance"],
  },
  {
    id: "sch-gates-cambridge",
    name: "Gates Cambridge Scholarship",
    slug: "gates-cambridge-scholarship",
    provider: "Bill and Melinda Gates Foundation",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    type: "organization",
    degree: ["masters", "phd"],
    funding: "fully_funded",
    amount: "Full tuition + £20,000/year + travel + development fund",
    deadline: "October 14 (US) / December 3 (International)",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["All countries outside UK"],
      ageLimit: null,
      gpa: 3.7,
      workExperience: null,
      languageRequirements: ["English proficiency"],
      documents: ["Academic transcripts", "Degree certificate", "CV", "Research proposal", "3 references", "Personal statement"],
    },
    benefits: ["Full tuition fees", "Living allowance £20,000/year", "Return airfare", "Development fund", "Family allowance", "Maternity/paternity funding"],
    applicationUrl: "https://www.gatescambridge.org/",
    contactEmail: "gatescambridge@gatescambridge.org",
    description: "Gates Cambridge Scholarships are awarded to outstanding postgraduate students from outside the UK to study at the University of Cambridge.",
    tips: ["Exceptional academic record required", "Strong research proposal", "Show leadership potential", "Demonstrate commitment to improving lives", "Apply early"],
    successRate: 10,
    competitive: true,
    renewable: false,
    duration: "1-4 years",
    coverage: ["Tuition", "Living expenses", "Travel", "Development"],
  },
  {
    id: "sch-rhodes",
    name: "Rhodes Scholarship",
    slug: "rhodes-scholarship",
    provider: "Rhodes Trust",
    country: "United Kingdom",
    countryCode: "GB",
    region: "Europe",
    type: "organization",
    degree: ["masters", "phd"],
    funding: "fully_funded",
    amount: "Full tuition + £18,000/year + airfare + health insurance",
    deadline: "October 1",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["USA, Canada, Australia, New Zealand, South Africa, Germany, India, China, and more"],
      ageLimit: 27,
      gpa: 3.7,
      workExperience: null,
      languageRequirements: ["English proficiency"],
      documents: ["Academic transcripts", "Degree certificate", "CV", "Personal statement", "10 references"],
    },
    benefits: ["Full tuition fees", "Annual stipend £18,000", "Return airfare", "Health insurance", "Access to Rhodes House", "Alumni network"],
    applicationUrl: "https://www.rhodeshouse.ox.ac.uk/",
    contactEmail: "registry@rhodeshouse.ox.ac.uk",
    description: "The Rhodes Scholarship is the oldest and most prestigious international scholarship, enabling outstanding young people to study at the University of Oxford.",
    tips: ["Exceptional academic and leadership record", "Community service important", "Strong personal statement", "Prepare for rigorous interview", "Show commitment to 'greater good'"],
    successRate: 8,
    competitive: true,
    renewable: false,
    duration: "2-3 years",
    coverage: ["Tuition", "Living expenses", "Travel"],
  },
  // ============================================
  // VANDERBILT UNIVERSITY SCHOLARSHIPS (USA)
  // ============================================
  {
    id: "sch-vanderbilt-cornelius",
    name: "Cornelius Vanderbilt Scholarship",
    slug: "cornelius-vanderbilt-scholarship",
    provider: "Vanderbilt University",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "university",
    degree: ["undergraduate"],
    funding: "fully_funded",
    amount: "Full tuition coverage (approx. $62,000/year)",
    deadline: "December 1",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["Domestic and International first-year undergraduate students"],
      ageLimit: null,
      gpa: null,
      workExperience: null,
      languageRequirements: ["TOEFL or IELTS for international students"],
      documents: ["Common Application or Coalition Application", "High school transcripts", "Two teacher recommendations", "Counselor recommendation", "SAT/ACT scores (optional)", "Supplemental essays"],
    },
    benefits: ["Full tuition coverage", "Renewable for 4 years", "Summer stipends for study abroad/research/service", "Leadership development opportunities", "Scholar communities and mentorship", "Priority course registration"],
    applicationUrl: "https://www.vanderbilt.edu/scholarships/",
    contactEmail: "vufinaid@vanderbilt.edu",
    description: "The Cornelius Vanderbilt Scholarship is Vanderbilt's most prestigious merit scholarship, covering full tuition for outstanding students who demonstrate academic excellence, leadership, and extracurricular accomplishment. Recipients represent the top 1% of applicants.",
    tips: ["Apply by December 1 deadline", "Demonstrate leadership and community impact", "Write compelling supplemental essays", "Show intellectual curiosity beyond classroom", "Highlight unique personal experiences", "Participate in optional interview if offered"],
    successRate: 5,
    competitive: true,
    renewable: true,
    duration: "4 years",
    coverage: ["Full tuition", "Summer stipends", "Leadership programs"],
  },
  {
    id: "sch-vanderbilt-ingram",
    name: "Ingram Scholars Program",
    slug: "ingram-scholars-program",
    provider: "Vanderbilt University",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "university",
    degree: ["undergraduate"],
    funding: "fully_funded",
    amount: "Full tuition coverage (approx. $62,000/year)",
    deadline: "December 1",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["Domestic and International first-year undergraduate students"],
      ageLimit: null,
      gpa: null,
      workExperience: null,
      languageRequirements: ["TOEFL or IELTS for international students"],
      documents: ["Common Application or Coalition Application", "High school transcripts", "Two teacher recommendations", "Counselor recommendation", "Ingram Scholars application supplement", "Essays on leadership and service"],
    },
    benefits: ["Full tuition coverage", "Renewable for 4 years", "Summer stipends", "Leadership and entrepreneurship training", "Community service projects", "Scholar cohort experience", "Mentorship from alumni network"],
    applicationUrl: "https://www.vanderbilt.edu/scholarships/ingram-scholars/",
    contactEmail: "vufinaid@vanderbilt.edu",
    description: "The Ingram Scholars Program supports students who demonstrate leadership, entrepreneurship, and a strong commitment to community service and social impact. Scholars engage in meaningful service projects and leadership development throughout their time at Vanderbilt.",
    tips: ["Show genuine passion for community service", "Demonstrate entrepreneurial thinking", "Provide evidence of leadership impact", "Write authentic essays about service experiences", "Apply by December 1 deadline", "Highlight specific social impact projects"],
    successRate: 5,
    competitive: true,
    renewable: true,
    duration: "4 years",
    coverage: ["Full tuition", "Service project funding", "Leadership programs"],
  },
  {
    id: "sch-vanderbilt-chancellor",
    name: "Chancellor's Scholarship",
    slug: "chancellors-scholarship-vanderbilt",
    provider: "Vanderbilt University",
    country: "United States",
    countryCode: "US",
    region: "North America",
    type: "university",
    degree: ["undergraduate"],
    funding: "fully_funded",
    amount: "Full tuition coverage (approx. $62,000/year)",
    deadline: "December 1",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["Domestic and International first-year undergraduate students"],
      ageLimit: null,
      gpa: null,
      workExperience: null,
      languageRequirements: ["TOEFL or IELTS for international students"],
      documents: ["Common Application or Coalition Application", "High school transcripts", "Two teacher recommendations", "Counselor recommendation", "Chancellor's Scholarship essays", "Evidence of leadership and diversity contributions"],
    },
    benefits: ["Full tuition coverage", "Renewable for 4 years", "Summer stipends", "Leadership development", "Access to scholar communities", "Mentorship programs", "Priority housing"],
    applicationUrl: "https://www.vanderbilt.edu/scholarships/chancellors-scholarship/",
    contactEmail: "vufinaid@vanderbilt.edu",
    description: "The Chancellor's Scholarship recognizes exceptional leadership, academic excellence, and contributions to diversity and inclusion. It is one of Vanderbilt's signature merit scholarships, awarded to students who have made significant impacts in their communities.",
    tips: ["Demonstrate commitment to diversity and inclusion", "Show leadership in creating positive change", "Write impactful essays about your journey", "Highlight community contributions", "Apply by December 1 deadline", "Show how you will contribute to Vanderbilt community"],
    successRate: 5,
    competitive: true,
    renewable: true,
    duration: "4 years",
    coverage: ["Full tuition", "Summer enrichment", "Leadership programs"],
  },
  // ============================================
  // ERASMUS MUNDUS & EU SCHOLARSHIP PROGRAMS
  // ============================================
  {
    id: "sch-erasmus-mundus-2",
    name: "Erasmus Mundus Joint Master Degree 2026",
    slug: "erasmus-mundus-joint-master-2026",
    provider: "European Commission (Erasmus+ Programme)",
    country: "European Union",
    countryCode: "EU",
    region: "Europe",
    type: "government",
    degree: ["masters"],
    funding: "fully_funded",
    amount: "€1,400/month stipend + full tuition + travel allowance + installation costs",
    deadline: "January 15 - March 15, 2026 (varies by consortium)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["All countries worldwide (180+ countries eligible)"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["Varies by program (English IELTS 6.0+ or equivalent)"],
      documents: ["Academic transcripts", "Bachelor's degree certificate", "Language certificate", "CV (Europass format)", "Motivation letter", "2 letters of recommendation", "Passport copy"],
    },
    benefits: [
      "Monthly living allowance €1,400",
      "Full tuition fee coverage",
      "Travel allowance",
      "Installation costs",
      "Health insurance",
      "Study in 2-3 European countries",
      "Access to EU academic network",
      "Erasmus+ alumni membership",
    ],
    applicationUrl: "https://erasmus-plus.ec.europa.eu/",
    contactEmail: "eac-erasmus-mundus@ec.europa.eu",
    description: "Erasmus Mundus Joint Master Degrees (EMJMDs) are prestigious, integrated, international study programs delivered by consortia of European higher education institutions. Students study in at least two different EU countries during their master's program, gaining a truly multicultural education experience. The program covers full tuition, provides a generous monthly stipend of €1,400, travel costs, and installation costs. With over 120+ joint master programs available across all academic disciplines, EMJMD is one of the most sought-after scholarships globally.",
    tips: [
      "Apply to multiple EMJMD consortia (max 3 applications)",
      "Start preparing 12-18 months before intended start",
      "Strong motivation letter highlighting international experience",
      "Check specific consortium deadlines (most close Feb-March)",
      "Research the specific programs and partner universities",
      "Demonstrate how the program fits your career goals",
      "Highlight any international or cross-cultural experience",
      "Get strong academic references",
    ],
    successRate: 20,
    competitive: true,
    renewable: false,
    duration: "1-2 years",
    coverage: ["Full tuition", "Living expenses", "Travel", "Health insurance", "Installation costs"],
  },
  {
    id: "sch-horizon-europe",
    name: "Horizon Europe Research Grants",
    slug: "horizon-europe-research-grants",
    provider: "European Commission",
    country: "European Union",
    countryCode: "EU",
    region: "Europe",
    type: "research",
    degree: ["phd", "postdoc", "research"],
    funding: "fully_funded",
    amount: "€3,000-€5,000/month + research costs + travel + institutional costs",
    deadline: "Rolling (varies by call)",
    deadlineType: "rolling",
    eligibility: {
      nationality: ["All countries worldwide (EU and non-EU researchers eligible)"],
      ageLimit: null,
      gpa: null,
      workExperience: 3,
      languageRequirements: ["English proficiency (B2+ level)"],
      documents: ["Research proposal", "CV (Europass)", "Publication list", "Host institution letter", "Ethics self-assessment"],
    },
    benefits: [
      "Monthly living allowance €3,000-€5,000",
      "Research costs coverage",
      "Travel and networking costs",
      "Institutional costs for host",
      "Access to EU research infrastructure",
      "Marie Skłodowska-Curie Actions label",
    ],
    applicationUrl: "https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/opportunities/topic-search;callCode=;freeTextSearchKeyword=horizon%20europe;matchWholeText=true;typeCodes=0,1;statusCodes=31094501,31094502;programCcm2Id=;programDivisionCode=;focusAreaCode=;destinationGroup=;missionGroup=;geographicalZonesCode=;program=;startDateLte=;startDateGte=;crossCuttingPriorityCode=;sbvCode=;whereClause=",
    contactEmail: "ec-horizon-europe@ec.europa.eu",
    description: "Horizon Europe is the EU's key funding programme for research and innovation with a budget of €95.5 billion. It supports excellent research and innovation through grants, prizes, and other instruments. The programme includes the European Research Council (ERC) grants, Marie Skłodowska-Curie Actions for researcher mobility, and collaborative research projects.",
    tips: [
      "Find a host institution in an EU country first",
      "Develop a strong, innovative research proposal",
      "Contact potential supervisors early",
      "Understand the evaluation criteria",
      "Consider interdisciplinary approaches",
      "Budget appropriately for all cost categories",
    ],
    successRate: 15,
    competitive: true,
    renewable: false,
    duration: "1-5 years",
    coverage: ["Research costs", "Living expenses", "Travel", "Institutional support"],
  },
  {
    id: "sch-marie-curie",
    name: "Marie Skłodowska-Curie Actions (MSCA)",
    slug: "marie-skodowska-curie-actions",
    provider: "European Commission",
    country: "European Union",
    countryCode: "EU",
    region: "Europe",
    type: "research",
    degree: ["phd", "postdoc", "research"],
    funding: "fully_funded",
    amount: "€3,400-€5,000/month + mobility allowance + family allowance",
    deadline: "September-October (varies by action type)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["All countries worldwide"],
      ageLimit: null,
      gpa: null,
      workExperience: null,
      languageRequirements: ["English proficiency"],
      documents: ["Research proposal", "CV", "Publication list", "Supervisor agreement", "Ethics self-assessment"],
    },
    benefits: [
      "Monthly living allowance €3,400-€5,000",
      "Mobility allowance (10% of living allowance)",
      "Family allowance (if applicable)",
      "Research training costs",
      "Overhead for host institution",
      "International and inter-sectoral mobility",
    ],
    applicationUrl: "https://ec.europa.eu/info/research-and-innovation/funding/funding-opportunities/funding-programmes-and-open-calls/horizon-europe/horizon-europe-msca_en",
    contactEmail: "ec-msca@ec.europa.eu",
    description: "Marie Skłodowska-Curie Actions (MSCA) support researchers at all stages of their careers and across all disciplines. The programme promotes excellence in research training, mobility, and career development. It includes Doctoral Networks (PhD training), Postdoctoral Fellowships (research mobility), and Staff Exchanges (institutional collaboration).",
    tips: [
      "Choose the right MSCA action for your career stage",
      "Doctoral Networks: Apply as a consortium partner",
      "Postdoctoral Fellowships: Find a strong host institution",
      "Emphasize the mobility dimension",
      "Highlight career development plan",
      "Address ethics and gender balance",
    ],
    successRate: 18,
    competitive: true,
    renewable: false,
    duration: "1-4 years",
    coverage: ["Living expenses", "Mobility", "Research training", "Career development"],
  },
  {
    id: "sch-erasmus-mundus-pakistan",
    name: "Erasmus Mundus for Pakistan Students",
    slug: "erasmus-mundus-pakistan-students",
    provider: "European Commission / HEC Pakistan",
    country: "European Union",
    countryCode: "EU",
    region: "Europe",
    type: "government",
    degree: ["masters"],
    funding: "fully_funded",
    amount: "€1,400/month + full tuition + travel + installation + health insurance",
    deadline: "January 15 - March 15, 2026",
    deadlineType: "annual",
    eligibility: {
      nationality: ["Pakistani nationals"],
      ageLimit: 35,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["IELTS 6.0+ or equivalent English proficiency"],
      documents: ["HEC attested transcripts", "Bachelor's degree", "English proficiency certificate", "CV", "Motivation letter", "2 recommendation letters", "NOC from HEC", "Passport copy"],
    },
    benefits: [
      "Monthly living allowance €1,400 (~PKR 420,000/month)",
      "Full tuition fee coverage",
      "Round-trip airfare allowance",
      "Installation costs",
      "Health insurance",
      "Study in 2-3 EU countries",
      "Access to 500,000+ EU university network",
      "Erasmus+ alumni network access",
    ],
    applicationUrl: "https://erasmus-plus.ec.europa.eu/",
    contactEmail: "hec@erasmusmundus.eu",
    description: "Pakistani students are among the top beneficiaries of the Erasmus Mundus program. The EU has strong partnerships with Pakistan's Higher Education Commission (HEC). Pakistani students can apply to over 120+ EMJMD programs across all disciplines. The scholarship provides full financial support including a generous monthly stipend, making it one of the most accessible fully-funded opportunities for Pakistani students to study in Europe.",
    tips: [
      "Register with HEC for NOC (No Objection Certificate) early",
      "Apply to at least 2-3 different EMJMD programs",
      "Strong IELTS score (6.5+ preferred) significantly helps",
      "Research partner universities in the consortium",
      "Prepare a compelling motivation letter",
      "Highlight how you will contribute to Pakistan's development",
      "Connect with Pakistani Erasmus alumni for guidance",
      "Apply well before deadlines (start 12 months ahead)",
    ],
    successRate: 25,
    competitive: true,
    renewable: false,
    duration: "1-2 years",
    coverage: ["Full tuition", "Living expenses", "Travel", "Health insurance", "Installation"],
  },
  {
    id: "sch-erasmus-mundus-india",
    name: "Erasmus Mundus for Indian Students",
    slug: "erasmus-mundus-indian-students",
    provider: "European Commission",
    country: "European Union",
    countryCode: "EU",
    region: "Europe",
    type: "government",
    degree: ["masters"],
    funding: "fully_funded",
    amount: "€1,400/month + full tuition + travel + installation",
    deadline: "January 15 - March 15, 2026",
    deadlineType: "annual",
    eligibility: {
      nationality: ["Indian nationals"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["IELTS 6.0+ or TOEFL 80+"],
      documents: ["Academic transcripts", "Bachelor's degree", "Language certificate", "CV", "Motivation letter", "2 recommendation letters", "Passport copy"],
    },
    benefits: [
      "Monthly living allowance €1,400",
      "Full tuition coverage",
      "Travel allowance",
      "Installation costs",
      "Health insurance",
      "Study in 2-3 European countries",
      "Erasmus+ alumni network",
    ],
    applicationUrl: "https://erasmus-plus.ec.europa.eu/",
    contactEmail: "erasmus.india@ec.europa.eu",
    description: "India is one of the largest sending countries for Erasmus Mundus. With strong academic partnerships between EU and Indian institutions, Indian students have excellent opportunities across STEM, social sciences, humanities, and more. The scholarship provides comprehensive financial support for a transformative European education experience.",
    tips: [
      "Check specific program requirements for Indian applicants",
      "Strong academic record significantly helps",
      "IELTS 6.5+ or TOEFL 90+ recommended",
      "Research EU-India academic partnerships",
      "Connect with Indian Erasmus alumni network",
      "Prepare a strong motivation letter",
    ],
    successRate: 22,
    competitive: true,
    renewable: false,
    duration: "1-2 years",
    coverage: ["Full tuition", "Living expenses", "Travel", "Health insurance"],
  },
  {
    id: "sch-eu-council-scholars",
    name: "EU Council Research Council (ERC) Grants",
    slug: "eu-erc-grants",
    provider: "European Research Council",
    country: "European Union",
    countryCode: "EU",
    region: "Europe",
    type: "research",
    degree: ["phd", "postdoc", "research"],
    funding: "fully_funded",
    amount: "€2-3 million over 5 years (Starter/Consolidator) / €3.5 million (Advanced)",
    deadline: "October-November (varies by grant type)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["All countries worldwide"],
      ageLimit: null,
      gpa: null,
      workExperience: 5,
      languageRequirements: ["English proficiency"],
      documents: ["Research proposal (max 15 pages)", "CV", "Publication list", "Host institution commitment", "Ethics self-assessment"],
    },
    benefits: [
      "Research grant €2-3.5 million over 5 years",
      "Personal salary component",
      "Research team funding",
      "Equipment and travel costs",
      "Indirect costs for host institution",
      "Complete research independence",
    ],
    applicationUrl: "https://erc.europa.eu/",
    contactEmail: "info@erc.europa.eu",
    description: "The European Research Council (ERC) provides grants to excellent researchers of any nationality based in the EU or associated countries. ERC grants support frontier research across all fields. Starting Grants (2-7 years post-PhD), Consolidator Grants (7-12 years post-PhD), and Advanced Grants (12+ years post-PhD) provide substantial funding for ambitious research projects.",
    tips: [
      "ERC values excellence above all - bold, innovative research",
      "Write a clear, compelling research proposal",
      "Demonstrate track record of high-quality publications",
      "Choose a host institution with strong research environment",
      "Address interdisciplinary potential",
      "Contact ERC laureates for advice",
    ],
    successRate: 12,
    competitive: true,
    renewable: false,
    duration: "5 years",
    coverage: ["Research costs", "Salary", "Team funding", "Equipment"],
  },
  {
    id: "sch-swedish-scholarship",
    name: "Swedish Institute Scholarships for Global Professionals (SISGP)",
    slug: "swedish-institute-scholarships",
    provider: "Swedish Institute",
    country: "Sweden",
    countryCode: "SE",
    region: "Europe",
    type: "government",
    degree: ["masters"],
    funding: "fully_funded",
    amount: "SEK 10,000/month + tuition + travel + insurance + grant",
    deadline: "February 2026",
    deadlineType: "annual",
    eligibility: {
      nationality: ["33 eligible countries including Pakistan, India, Bangladesh, Nigeria, Kenya, etc."],
      ageLimit: null,
      gpa: 3.0,
      workExperience: 3000,
      languageRequirements: ["IELTS 6.5+ or TOEFL 90+"],
      documents: ["Academic transcripts", "Degree certificate", "Work experience certificate", "IELTS/TOEFL", "CV", "Motivation letter", "References"],
    },
    benefits: [
      "Monthly living allowance SEK 10,000",
      "Full tuition fee coverage",
      "Travel grant",
      "Insurance coverage",
      "Membership in SI alumni network",
      "Career development programs",
    ],
    applicationUrl: "https://si.se/en/apply/scholarships/sisgp/",
    contactEmail: "info@si.se",
    description: "The Swedish Institute Scholarships for Global Professionals (SISGP) target talented professionals from eligible countries who want to pursue a master's degree in Sweden. The scholarship aims to develop future leaders who will contribute to sustainable development in their home countries.",
    tips: [
      "Must have minimum 3,000 hours of work experience",
      "Demonstrate leadership potential",
      "Show commitment to sustainable development",
      "Choose from 600+ English-taught master's programs",
      "Apply for university admission simultaneously",
    ],
    successRate: 20,
    competitive: true,
    renewable: false,
    duration: "1-2 years",
    coverage: ["Tuition", "Living expenses", "Travel", "Insurance"],
  },
  {
    id: "sch-holland-scholarship",
    name: "Holland Scholarship",
    slug: "holland-scholarship",
    provider: "Dutch Ministry of Education",
    country: "Netherlands",
    countryCode: "NL",
    region: "Europe",
    type: "government",
    degree: ["bachelors", "masters"],
    funding: "partial",
    amount: "€5,000 (one-time, first year only)",
    deadline: "February 1 / May 1 (varies by university)",
    deadlineType: "annual",
    eligibility: {
      nationality: ["Non-EEA countries"],
      ageLimit: null,
      gpa: 3.0,
      workExperience: null,
      languageRequirements: ["IELTS 6.0+ or TOEFL 80+"],
      documents: ["Academic transcripts", "Degree certificate", "Language certificate", "Motivation letter"],
    },
    benefits: [
      "One-time grant of €5,000",
      "Can be combined with other scholarships",
      "Access to Dutch university system",
    ],
    applicationUrl: "https://www.studyinholland.nl/finances/scholarships",
    contactEmail: "info@studyinholland.nl",
    description: "The Holland Scholarship is for non-EEA students who want to study in the Netherlands. It's a one-time scholarship of €5,000 awarded in the first year of study. The scholarship can be combined with other funding sources.",
    tips: [
      "Apply to participating Dutch universities early",
      "Can be combined with tuition fee waivers",
      "Demonstrate why Netherlands fits your study goals",
      "Check specific university deadlines",
    ],
    successRate: 30,
    competitive: false,
    renewable: false,
    duration: "1 year (one-time)",
    coverage: ["Partial tuition support"],
  },
  {
    id: "sch-eth-zurich-excellence",
    name: "ETH Zurich Excellence Scholarships",
    slug: "eth-zurich-excellence-scholarships",
    provider: "ETH Zurich",
    country: "Switzerland",
    countryCode: "CH",
    region: "Europe",
    type: "university",
    degree: ["masters", "phd"],
    funding: "fully_funded",
    amount: "CHF 12,000/semester stipend + full tuition waiver",
    deadline: "December 15 (masters) / varies (PhD)",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["All countries worldwide"],
      ageLimit: null,
      gpa: 3.7,
      workExperience: null,
      languageRequirements: ["English or German proficiency"],
      documents: ["Academic transcripts", "Degree certificate", "CV", "Motivation letter", "2 recommendation letters", "Research proposal (PhD)"],
    },
    benefits: [
      "CHF 12,000 per semester stipend",
      "Full tuition fee waiver",
      "Access to world-class research facilities",
      "Mentorship from leading professors",
      "ETH alumni network",
    ],
    applicationUrl: "https://ethz.ch/en/studies/financial/scholarships.html",
    contactEmail: "info@ethz.ch",
    description: "ETH Zurich is ranked #7 globally and offers Excellence Scholarships to outstanding students. The scholarship covers the full cost of study and provides a generous stipend. ETH Zurich is one of the world's leading universities in science and technology.",
    tips: [
      "Exceptional academic record required (top 5% of class)",
      "Strong recommendation letters from professors",
      "Demonstrate research interest aligned with ETH faculty",
      "Apply before December 15 deadline",
      "Consider ETH's specific admission requirements",
    ],
    successRate: 10,
    competitive: true,
    renewable: true,
    duration: "1-3 years",
    coverage: ["Tuition", "Living expenses"],
  },
  {
    id: "sch-ecole-poly-scholarship",
    name: "EPFL Excellence Scholarships",
    slug: "ecole-polytechnique-federale-scholarships",
    provider: "EPFL (Swiss Federal Institute of Technology)",
    country: "Switzerland",
    countryCode: "CH",
    region: "Europe",
    type: "university",
    degree: ["masters", "phd"],
    funding: "fully_funded",
    amount: "CHF 16,000/year + full tuition waiver",
    deadline: "December 15 (masters)",
    deadlineType: "fixed",
    eligibility: {
      nationality: ["All countries worldwide"],
      ageLimit: null,
      gpa: 3.7,
      workExperience: null,
      languageRequirements: ["English proficiency"],
      documents: ["Academic transcripts", "Degree certificate", "CV", "Motivation letter", "2 recommendation letters"],
    },
    benefits: [
      "CHF 16,000 annual stipend",
      "Full tuition fee waiver",
      "Access to cutting-edge research labs",
      "International study environment",
    ],
    applicationUrl: "https://www.epfl.ch/education/master/programs/admission/scholarships/",
    contactEmail: "admissions@epfl.ch",
    description: "EPFL is ranked among the top 20 universities globally and offers Excellence Scholarships to outstanding master's students. Located in Lausanne, Switzerland, EPFL is a world-leading institution in science and technology.",
    tips: [
      "Top academic record required",
      "Strong STEM background",
      "Research experience valued",
      "Apply before December deadline",
    ],
    successRate: 12,
    competitive: true,
    renewable: true,
    duration: "1.5-2 years",
    coverage: ["Tuition", "Living expenses"],
  },
];

// GET /api/scholarships/comprehensive - Get all scholarships
export async function GET(request: Request) {
  try {
    const url = new URL(request.url);
    const country = url.searchParams.get("country");
    const provider = url.searchParams.get("provider");
    const degree = url.searchParams.get("degree");
    const funding = url.searchParams.get("funding");
    const search = url.searchParams.get("search");
    const sortBy = url.searchParams.get("sortBy") || "name";
    const limit = parseInt(url.searchParams.get("limit") || "50");

    let results = [...scholarshipDatabase];

    if (country) results = results.filter((s) => s.country.toLowerCase().includes(country.toLowerCase()));
    if (provider) results = results.filter((s) => s.provider.toLowerCase().includes(provider.toLowerCase()));
    if (degree) results = results.filter((s) => s.degree.includes(degree));
    if (funding) results = results.filter((s) => s.funding === funding);
    if (search) {
      const q = search.toLowerCase();
      results = results.filter(
        (s) =>
          s.name.toLowerCase().includes(q) ||
          s.description.toLowerCase().includes(q) ||
          s.country.toLowerCase().includes(q)
      );
    }

    if (sortBy === "competitive") results.sort((a, b) => a.competitive === b.competitive ? 0 : a.competitive ? -1 : 1);
    else if (sortBy === "deadline") results.sort((a, b) => a.deadline.localeCompare(b.deadline));
    else if (sortBy === "country") results.sort((a, b) => a.country.localeCompare(b.country));
    else results.sort((a, b) => a.name.localeCompare(b.name));

    results = results.slice(0, limit);

    const meta: Record<string, string[]> = {
      sources: ["Fulbright", "DAAD", "Chevening", "Erasmus+", "Commonwealth", "MEXT", "CSC", "Stipendium Hungaricum", "Gates Cambridge", "Rhodes", "Vanderbilt University"],
    };

    return NextResponse.json({
      success: true,
      data: results,
      meta,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, error: error instanceof Error ? error.message : "Failed to fetch scholarships" },
      { status: 500 }
    );
  }
}
